site_name: Fast Grego
site_description: Documentação do Fast Grego
repo_url: https://github.com/fast-grego
site_dir: site
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'images/icon.png'
  favicon: 'images/icon.png'
  palette:
    primary: 'red'
  language: 'pt'

plugins:
  - search
nav:
  - Home: 'index.md'
  - Modelo conceitual: 'modelo-conceitual/index.md'
  - Geração de alternativas: 'geracao-alternativas/index.md'
  - Prototipagem: 'prototipagem/index.md'