site_name: Fast Grego
site_description: Documentação do Fast Grego
repo_url: https://github.com/fast-grego
site_dir: site
dev_addr: ‘0.0.0.0:8000
theme:
  name: 'material'
  logo: 'images/icon.png'
  favicon: 'images/icon.png'
  palette:
    primary: 'red'
  language: 'pt'

plugins:
  - search
nav:
  - Home: 'index.md'
  - Modelo conceitual: 'modelo-conceitual/index.md'
  - Geração de alternativas: 'geracao-alternativas/index.md'
  - Requisitos: 'requisitos/index.md'
  - Teste de Usuabilidade:
    - Roteiro: 'teste-de-usuabilidade/roteiro-teste-usuabilidade.md'
    - Resultados: 'teste-de-usuabilidade/resultados-teste-usuabilidade.md'
  - Prototipagem: 
    - Baixa fidelidade: 'prototipagem/baixa-fidelidade.md'
    - Média fidelidade: 'prototipagem/media-fidelidade.md'
    - Alta fidelidade: 'prototipagem/alta-fidelidade.md'